config/routes.rb
Timeclock::Application.routes.draw do
  resources :time_zones

  resources :punches
  resources :employees

  root :to => "punches#new"

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :last_name, :first_name, :enabled
  cattr_reader :per_page
  has_many :punches
  validates_presence_of :last_name, :first_name
  
  @@per_page = 1
  
  def display_name
    "#{last_name}, #{first_name}"
  end
  
end

app/models/punch.rb
class Punch < ActiveRecord::Base
  attr_accessible :employee_id, :in, :created_at
  belongs_to :employee, :conditions => {:enabled => true}
  validates_presence_of :employee_id, :in
end

app/models/time_zone.rb
class TimeZone < ActiveRecord::Base
  attr_accessible :time_zone
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :set_time_zone
  USER_NAME, PASSWORD = "admin", "secret"
  protect_from_forgery
  
  private
  
    def set_time_zone
      if TimeZone.first
        Time.zone = TimeZone.first.time_zone
      else
        Time.zone = "UTC"
      end
    end
  
    def authenticate
    	authenticate_or_request_with_http_basic do |user_name, password|
    		user_name == USER_NAME && password == PASSWORD
		end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	before_filter :authenticate

  def index
    @employees = Employee.all()
  end
  
  def show
    @employee = Employee.find(params[:id])
  end
  
  def new
    @employee = Employee.new
  end
  
  def create
    @employee = Employee.new(params[:employee])
    if @employee.save
      flash[:notice] = "Successfully created employee."
      redirect_to @employee
    else
      render :action => 'new'
    end
  end
  
  def edit
    @employee = Employee.find(params[:id])
  end
  
  def update
    @employee = Employee.find(params[:id])
    if @employee.update_attributes(params[:employee])
      flash[:notice] = "Successfully updated employee."
      redirect_to @employee
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    flash[:notice] = "Successfully destroyed employee."
    redirect_to employees_url
  end
end

app/controllers/punches_controller.rb
class PunchesController < ApplicationController
	
	before_filter :authenticate, :except => [ :new, :show, :create ]
	
  def index
    @punches = Punch.all(:order => "punches.employee_id desc")
    @employees = Employee.paginate(:page => params[:page], :order => "last_name, first_name", :conditions => {:enabled => true})
    # @employees = Employee.find(:all, :order => "last_name", :conditions => {:enabled => true})
    # @punches = Punch.paginate(:page => params[:page], :order => "punches.employee_id")
  end
  
  def show
    @punch = Punch.find(params[:id])
  end
  
  def new
    @punch = Punch.new
  end
  
  def create
    @punch = Punch.new(params[:punch])
    if @punch.save
      flash[:notice] = "Successfully created punch."
      redirect_to @punch
    else
      render :action => 'new'
    end
  end
  
  def edit
    @punch = Punch.find(params[:id])
  end
  
  def update
    @punch = Punch.find(params[:id])
    if @punch.update_attributes(params[:punch])
      flash[:notice] = "Successfully updated punch."
      redirect_to @punch
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @punch = Punch.find(params[:id])
    @punch.destroy
    flash[:notice] = "Successfully destroyed punch."
    redirect_to punches_url
  end
end

app/controllers/time_zones_controller.rb
class TimeZonesController < ApplicationController
  before_filter :authenticate
  
  def index
    @time_zones = TimeZone.all
  end
  
  def show
    @time_zone = TimeZone.find(params[:id])
  end
  
  def new
    @time_zone = TimeZone.new
  end
  
  def create
    @time_zone = TimeZone.new(params[:time_zone])
    if @time_zone.save
      flash[:notice] = "Successfully created time zone."
      redirect_to @time_zone
    else
      render :action => 'new'
    end
  end
  
  def edit
    @time_zone = TimeZone.find(params[:id])
  end
  
  def update
    @time_zone = TimeZone.find(params[:id])
    if @time_zone.update_attributes(params[:time_zone])
      flash[:notice] = "Successfully updated time zone."
      redirect_to @time_zone
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @time_zone = TimeZone.find(params[:id])
    @time_zone.destroy
    flash[:notice] = "Successfully destroyed time zone."
    redirect_to time_zones_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options! 
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end
  
  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/punches_helper.rb
module PunchesHelper
end

app/helpers/time_zones_helper.rb
module TimeZonesHelper
end

app/views/employees/_form.html.haml
= semantic_form_for @employee do |f|
  = f.inputs
  = f.buttons

app/views/employees/edit.html.haml
- title "Edit Employee"

= render 'form'

%p
  = link_to "Show", employee_path(@employee)
  |
  = link_to "View All", employees_path

app/views/employees/index.html.haml
- title "Employees"

%p= link_to "Punch List", punches_path

%table
  %tr
    %th Last name
    %th First name
    %th Enabled
  - for employee in @employees
    %tr
      %td= employee.last_name
      %td= employee.first_name
      %td= employee.enabled
      %td= link_to 'Show', employee
      %td= link_to 'Edit', edit_employee_path(employee)
      %td= link_to 'Destroy', employee, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Employee", new_employee_path

app/views/employees/new.html.haml
- title "New Employee"

= render 'form'

%p= link_to "Back to List", employees_path

app/views/employees/show.html.haml
- title "Employee"

%p
  %strong Last Name:
  = @employee.last_name
%p
  %strong First Name:
  = @employee.first_name
%p
  %strong Enabled:
  = @employee.enabled

%p
  = link_to "Edit", edit_employee_path(@employee)
  |
  = link_to "Destroy", @employee, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", employees_path

app/views/layouts/_menu.html.haml
%li= link_to "New Punch", new_punch_path
%li= link_to "Timesheets", punches_path
%li= link_to "New Employee", new_employee_path
%li= link_to "Set TimeZone", time_zones_path

app/views/layouts/application.html.haml
!!!
%html 
  
  %head
    %title
      = yield(:title) || "Untitled"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag "application", "formtastic", "formtastic_changes", :cache => "base"
    = javascript_include_tag :defaults
    = csrf_meta_tag
    = yield(:head)
  
  %body
    #container
      
      %ul#menu
        = render "layouts/menu"
      %br
    
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"
        
      %br
      
      - if show_title?
        %h1= yield(:title)
      
      = yield

app/views/punches/_form.html.haml
= semantic_form_for @punch do |f|
  / = f.error_messages
  = f.inputs do
    = f.input :employee, :collection => Employee.find(:all, :order => "last_name")
    = f.input :in, :as => :radio, :label => "Punch", :collection => [["In", 1], ["Out", 2]]
    = f.input :created_at if params[:action] == "edit"
  = f.buttons do
    = f.commit_button :label => "Punch It!"

app/views/punches/edit.html.haml
- title "Edit Punch"

= render 'form'

%p
  = link_to "Show", punch_path(@punch)
  |
  = link_to "View All", punches_path

app/views/punches/index.html.haml
- title "Timesheet", false

= will_paginate @employees, :previous_label => "< prev", :next_label => "next >", :separator => " | "

- @employees.each do |emp|
  - total_time = 0
  %h2= emp.display_name
  - 1.week.ago.beginning_of_week.to_date.upto(1.week.ago.end_of_week.to_date) do |date|
    - punch_list = emp.punches.find(:all, :conditions => {:created_at => date.to_time..date.to_time+1.day})
    - next if !punch_list.first
    - time_in = 0
    - time_out = 0
    %h4.time_week_day= "#{Date::DAYNAMES[date.wday]} - #{date.month}/#{date.mday}"
    - if punch_list.count % 2 > 0
      %strong.time_missing_punch= "Error: Missing Punch"
    %table
      - punch_list.each do |punch|
        - punch.in == 1 ? time_in = time_in + punch.created_at.to_f : time_out = time_out + punch.created_at.to_f
        %tr
          %td= punch.in == 1 ? "In" : "Out"
          %td= punch.created_at.strftime("%I:%M:%S %p")
          %td= link_to 'Edit', edit_punch_path(punch)
          %td= link_to 'Delete', punch, :confirm => 'Are you sure?', :method => :delete
    - time_today = (time_out - time_in)/60/60
    %h4.time_total_daily= "#{sprintf('%.3f', time_today)} hours"
    - total_time = total_time + (time_out - time_in)
  %h3.time_total_weekly= "#{sprintf('%.3f', total_time/60/60)} hours"

app/views/punches/new.html.haml
- title "Timeclock"
= render 'form'
  

app/views/punches/show.html.haml
- title "Punch", false

%p
  %strong Employee:
  = @punch.employee.display_name
%p
  %strong Punched:
  = @punch.in == 1 ? "In" : "Out"
%p
  %strong Time:
  = @punch.created_at.strftime("%I:%M:%S %p")

app/views/time_zones/_form.html.erb
<%= form_for @time_zone do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :time_zone %><br />
    <%= f.time_zone_select :time_zone %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/time_zones/edit.html.erb
<% title "Edit Time Zone" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @time_zone %> |
  <%= link_to "View All", time_zones_path %>
</p>

app/views/time_zones/index.html.erb
<% title "Time Zones" %>

<table>
  <tr>
    <th>Time Zone</th>
  </tr>
  <% for time_zone in @time_zones %>
    <tr>
      <td><%= time_zone.time_zone %></td>
      <td><%= link_to "Show", time_zone %></td>
      <td><%= link_to "Edit", edit_time_zone_path(time_zone) %></td>
      <td><%= link_to "Destroy", time_zone, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Time Zone", new_time_zone_path %></p>

app/views/time_zones/new.html.erb
<% title "New Time Zone" %>

<%= render 'form' %>

<p><%= link_to "Back to List", time_zones_path %></p>

app/views/time_zones/show.html.erb
<% title "Time Zone" %>

<p>
  <strong>Time Zone:</strong>
  <%= @time_zone.time_zone %>
</p>

<p>
  <%= link_to "Edit", edit_time_zone_path(@time_zone) %> |
  <%= link_to "Destroy", @time_zone, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", time_zones_path %>
</p>